services:
  - type: web
    name: miniamazon-api
    runtime: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/server.js
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
